spring:
  datasource:
    url: jdbc:h2:file:./data/exercicio
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

domain:
  viacep: http://viacep.com.br/ws
  viacep-name: viacep
